Claim all Alpha token rewards for user as a lender and borrower then create receipt
AlphaFinanceLab/alpha-lending-smart-contract pull request #1
Opened 2020-09-10 15:23 UTC by mizu-mochi

2020-09-11 04:21 UTC, false10 requested changes

2020-09-11 04:21 UTC, false10 commented on contracts/AlToken.sol
> +    claimCurrentAlphaReward(_account);
Add `setLatestReward` after claim.

2020-09-14 09:27 UTC, mizu-mochi commented on contracts/AlToken.sol
> +    claimCurrentAlphaReward(_account);
Add on `claimCurrentAlphaReward`

2020-09-14 15:31 UTC, false10 requested changes

2020-09-14 15:31 UTC, false10 commented on contracts/AlToken.sol
> +    setLatestAlphaMultiplier(_account);
No need to setLatestAlphaMultiplier?

2020-09-14 15:31 UTC, false10 commented on contracts/AlToken.sol
> +    setLatestAlphaMultiplier(_account);
ditto

2020-09-14 15:31 UTC, false10 commented on contracts/AlToken.sol
> +    setLatestAlphaMultiplier(_account);
I think this internal function not necessary anymore.

2020-09-14 15:31 UTC, false10 commented on contracts/AlToken.sol
> +    setLatestAlphaMultiplier(_to);
ditto

2020-09-14 17:30 UTC, false10 approved these changes

2020-09-14 17:30 UTC, merged